# To change the log file location, replace the roller.path and  
# roller.policy.roller.pattern values below.  fout.path will also
# need to be change if it's being used.
#
# By default, rootdir = ~/.tms.  Note that shell macros like ~ 
# cannot be used in this file; use an absoluted path instead,
#
# Note the use of the jinja2-like template variable: {{TMS_ROOT_DIR}}.
# This placeholder variable gets replaced by the rootdir on new 
# installations of the tms_server.  This is a one time replacement when
# a new, non-existing rootdir is specified.  If this file is copied to 
# a new rootdir after installation, manual adjustment of the paths 
# configured in this file will be necessary. 

refresh_rate: 60 seconds

appenders:
  stdout:
    kind: console
    encoder:
      pattern: "{d(%Y-%m-%dT%H:%M:%S.%f)(utc)}Z {l:<5} [{T}] {f:>.100}:{L} - {m}{n}"

#  fout:
#    kind: file
#    path: "{{TMS_ROOT_DIR}}/logs/tms.log"
#    encoder:
#      pattern: "{d(%Y-%m-%dT%H:%M:%S.%f)(utc)}Z {l:<5} [{T}] {f:>.100}:{L} - {m}{n}"

  roller:
    kind: rolling_file
    append: true
    path: "{{TMS_ROOT_DIR}}/logs/tms_roller.log"
    encoder:
      kind: pattern
      pattern: "{d(%Y-%m-%dT%H:%M:%S.%f)(utc)}Z {l:<5} [{T}] {f:>.100}:{L} - {m}{n}"
    policy:
      kind: compound
      trigger:
        kind: size
        limit: 20 mb
      roller:
        kind: fixed_window
        base: 1
        count: 3
        pattern: "{{TMS_ROOT_DIR}}/logs/tms_roller{}.log"
        
root:
  level: info
  appenders:
    - stdout
    - roller

# loggers:
#   rust-logtest2:
#     level: trace
#     appenders:
#       - stdout
#     additive: false
