# Replace <PUT_YOUR_ROOTDIR_HERE> with TMS's configured rootdir. 
# By default, rootdir = ~/.tms.  Note that shell macros like ~ 
# cannot be used in this file; use an absoluted path instead,

refresh_rate: 60 seconds

appenders:
  stdout:
    kind: console
    encoder:
      pattern: "{d(%Y-%m-%dT%H:%M:%S.%f)(utc)}Z {l:<5} [{T}] {f:>.100}:{L} - {m}{n}"

#  fout:
#    kind: file
#    path: "<PUT_YOUR_ROOTDIR_HERE>/logs/tms.log"
#    encoder:
#      pattern: "{d(%Y-%m-%dT%H:%M:%S.%f)(utc)}Z {l:<5} [{T}] {f:>.100}:{L} - {m}{n}"

  roller:
    kind: rolling_file
    append: true
    path: "<PUT_YOUR_ROOTDIR_HERE>/logs/tms_roller.log"
    encoder:
      kind: pattern
      pattern: "{d(%Y-%m-%dT%H:%M:%S.%f)(utc)}Z {l:<5} [{T}] {f:>.100}:{L} - {m}{n}"
    policy:
      kind: compound
      trigger:
        kind: size
        limit: 20 mb
      roller:
        kind: fixed_window
        base: 1
        count: 3
        pattern: "<PUT_YOUR_ROOTDIR_HERE>/logs/tms_roller{}.log"
        
root:
  level: debug
  appenders:
    - stdout
    - roller

# loggers:
#   rust-logtest2:
#     level: trace
#     appenders:
#       - stdout
#     additive: false
