openapi: 3.1.0
info:
  title: Trust Manager System (TMS) Server
  description: |
    The Trust Manager System (TMS) server provides for management of credentials by a trusted application client.
  version: '0.3.0'
  termsOfService: "https://tapis-project.org"
  contact:
    name: "TMS Server - CICSupport"
    url: "https://tapis-project.org"
    email: "cicsupport@tacc.utexas.edu"
  license:
    name: 3-Clause BSD License
    url: 'https://opensource.org/licenses/BSD-3-Clause'
externalDocs:
  description: Tapis Project
  url: 'https://tapis-project.org'
servers:
  - url: 'http://localhost:3000/'
    description: Local test environment
    variables: {}
tags:
  - name: General
    description: General service health and readiness
  - name: Credentials
    description: Manage access credentials

# ------------------------------------------------------------------------------
# --- Paths -------------------------------------------------------------------
# ------------------------------------------------------------------------------
paths:

  # --- sayHello and getVersion ------------------------------------------------
  '/tms/hello':
    get:
      tags:
        - General
      description: Echo a query parameter.
      operationId: sayHello
      parameters:
        - name: name
          schema:
            type: string
          in: query
      responses:
        '200':
          description: Success.
          content:
            text/plain; charset=utf-8:
              schema:
                type: string
  '/tms/version':
    get:
      tags:
        - General
      description: Return server version information.
      operationId: getVersion
      responses:
        '200':
          description: Success.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RespVersion'
        '500':
          description: Server error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpResult'

  # --- createSshKeypair -------------------------------------------------------
  '/tms/pubkeys/creds':
    post:
      tags:
        - Credentials
      description: |
        Create an ssh keypair using provided values for client user, host, host account, number of uses, TTL minutes
        and key type. All values are required except for key type, which defaults to ED25519. Supported values for
        key type (case insensitive): ED25519, ECDSA, RSA.
        
        *WARNING* Note that in the current MVP implementation the number of uses and TTL minutes are ignored.
        In a future release of TMS Server, these attributes will be honored.
        
        *In a future release*, setting the number of uses or TTL minutes to a negative value results in maximum limits.
        If both are negative this effectively creates a keypair with no limits.
        If both are specified as 0 then the resulting key is not usable.
      operationId: createSShKeypair
      requestBody:
        required: true
        description: A JSON object providing information about the SSH keypair ot be generated.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ReqNewSshKeypair'
      responses:
        '201':
          description: Keypair created.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RespNewSshKeypair'

  # --- retrievePubKey --------------------------------------------------------------
  '/tms/pubkeys/creds/retrieve':
    post:
      tags:
        - Credentials
      description: |
        Retrieve public key using provided values for user, host and public key fingerprint. Values may also be
        provided for user UID and key type, but these are only used for writing to the server side log.
        
        The user and host must match the host account and host provided when the keypair was generated. If a match is
        found the public key is returned as part of the result.
      operationId: retrievePubKey
      requestBody:
        required: true
        description: A JSON object providing information about the SSH public key to be retrieved.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ReqGetPublicKey'
      responses:
        '200':
          description: Public key found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RespGetPublicKey'

# ------------------------------------------------------------------------------
# --- Components ---------------------------------------------------------------
# ------------------------------------------------------------------------------
components:
  schemas:
    # -------------------------------------------------------------------------
    # --- Request objects -----------------------------------------------------
    # -------------------------------------------------------------------------
    ReqNewSshKeypair:
      type: object
      required:
        - client_user_id
        - host
        - host_account
        - num_uses
        - ttl_minutes
      properties:
        client_user_id:
          type: string
          description: User associated with the Resource Provider
        host:
          type: string
          description: FQDN for the host where the user has an account.
        host_account:
          type: string
          description: Username of the host account.
        num_uses:
          type: integer
          format: int32
          description: Number of allowed uses. *WARNING* Not yet supported.
        ttl_minutes:
          type: integer
          format: int32
          description: TTL in minutes. *WARNING* Not yet supported.
        key_type:
          $ref: '#/components/schemas/SshKeyTypeEnum'
    ReqGetPublicKey:
      type: object
      required:
        - user
        - host
        - public_key_fingerprint
      properties:
        user:
          type: string
          description: Username of the host account.
        user_uid:
          type: string
          description: UID of the host account. Info only. Not used for lookup.
        host:
          type: string
          description: FQDN for the host where the user has an account.
        public_key_fingerprint:
          type: string
          description: Fingerprint of the SSH public key.
        key_type:
          type: string
          description: Type of SSH Key. For example ssh-ed25519 or ssh-rsa. Info only. Not used for lookup.

    # -------------------------------------------------------------------------
    # --- Response objects ----------------------------------------------------
    # -------------------------------------------------------------------------
    RespVersion:
      type: object
      properties:
        result_code:
          type: string
        result_msg:
          type: string
        tms_version:
          type: string
        git_branch:
          type: string
        git_commit:
          type: string
        git_dirty:
          type: string
        source_ts:
          type: string
        rustc_version:
          type: string
    HttpResult:
      type: object
      required:
        - result_code
        - result_msg
      properties:
        result_code:
          type: string
        result_msg:
          type: string
    RespNewSshKeypair:
      type: object
      properties:
        result_code:
          type: string
        result_msg:
          type: string
        private_key:
          type: string
        public_key:
          type: string
        public_key_fingerprint:
          type: string
        key_type:
          type: string
        key_bits:
          type: string
        max_uses:
          type: string
        remaining_uses:
          type: string
        expires_at:
          type: string
          format: date-time
    RespGetPublicKey:
      type: object
      properties:
        result_code:
          type: string
        result_msg:
          type: string
        public_key:
          type: string

    # -------------------------------------------------------------------------
    # --- Enums ---------------------------------------------------------------
    # -------------------------------------------------------------------------
    SshKeyTypeEnum:
      type: string
      description: Type of ssh key
      enum:
        - ED25519
        - RSA
        - ECDSA