#!/bin/bash
# Script to run tms_server docker image container in the first time install mode.
# TMS DB user password must be set in TMS_DB_USER_PASSWORD
#
# This script ....TODO/TBD???c
#   

export TMS_DB_HOST="${TMS_DB_HOST:-tms-postgres-18}"
export TMS_DB_PORT="${TMS_DB_PORT:-5432}"

if [ -z "${TMS_DB_USER_PASSWORD}" ]; then
  echo "Please set env var TMS_DB_USER_PASSWORD before running this script"
  exit 1
fi

# TODO
# Run tms_server in first time install mode
# TODO/TBD We are inside the pod.
cd /home/tms/tms_server || exit 1
./tms_server --root-dir /home/tms/tms --install > /home/tms/tms_local/tms-install.out 2>&1
