apiVersion: batch/v1
kind: Job
metadata:
  name: tms-first-time-install
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: tms-first-time-install
        image: tapis/tms-server:dev
        imagePullPolicy: Always
        command: ["cd /home/tms/tms_server; ./tms_server --root-dir /home/tms/tms --install > /home/tms/tms_local/tms-install.out 2>&1"]
        restartPolicy: never
        volumeMounts:
        - name: tms-server-vol
          mountPath: /home/tms
        env:
        - name: TMS_DB_USER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: tms-secrets
              key: postgres-tms-user-password
      volumes:
      - name: tms-server-vol
  backoffLimit: 4
