# Put yml here for pvc to be used by TMS server
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: tms-server-vol
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: cinder-csi
  resources:
    requests:
      storage: 10Gi
