#!/bin/bash
# Script to initialize and setup the TMS Server service
# Create database, user and schema
# Postgres password must be set in env var POSTGRES_PASSWORD
#   and TMS DB user password must be set in TMS_DB_USER_PASSWORD
#
# This script creates the TMS DB and user (i.e. schema) and
#   runs the tms_server docker image in first time setup mode.

TMS_DB_HOST="${TMS_DB_HOST:-tms-postgres-18}"
TMS_DB_PORT="${TMS_DB_PORT:-5432}"
DB_USER=postgres
DB_NAME=tmsdb
export TMS_DB_SCHEMA=tms
export TMS_DB_USER=tms

PSQL_CMD="psql --host=${TMS_DB_HOST} --port=${TMS_DB_PORT}"

if [ -z "${POSTGRES_PASSWORD}" ]; then
  echo "Please set env var POSTGRES_PASSWORD before running this script"
  exit 1
fi

# Put PGPASSWORD in environment for psql to pick up
export PGPASSWORD=${POSTGRES_PASSWORD}

# Remove the schema, user and database
$PSQL_CMD --username=${DB_USER} -q << EOB
DROP SCHEMA IF EXISTS ${TMS_DB_SCHEMA} CASCADE;
DROP USER IF EXISTS ${TMS_DB_USER};
DROP DATABASE IF EXISTS ${DB_NAME}
EOB
