#!/bin/bash
# Script to initialize and setup the TMS Server service
# Create database, user and schema
# Postgres password must be set in env var POSTGRES_PASSWORD
#   and TMS DB user password must be set in TMS_DB_USER_PASSWORD
#
# This script creates the TMS DB and user (i.e. schema) and
#   runs the tms_server docker image in first time setup mode.

TAPIS_DB_HOST="${TMS_DB_HOST:-tms-postgres-18}"
TAPIS_DB_PORT="${TMS_DB_PORT}:-5432"
DB_USER=postgres
DB_NAME=tmsdb
export TMS_DB_SCHEMA=tms

PSQL_CMD="psql --host=${TAPIS_DB_HOST} --port=${TAPIS_DB_PORT}"

if [ -z "${POSTGRES_PASSWORD}" ]; then
  echo "Please set env var POSTGRES_PASSWORD before running this script"
  exit 1
fi
if [ -z "${TMS_DB_USER_PASSWORD}" ]; then
  echo "Please set env var TMS_DB_USER_PASSWORD before running this script"
  exit 1
fi


# Put PGPASSWORD in environment for psql to pick up
export PGPASSWORD=${POSTGRES_PASSWORD}

# Run psql command to create database if it does not exist
echo "SELECT 'CREATE DATABASE ${DB_NAME} ENCODING=\"UTF8\" LC_COLLATE=\"en_US.utf8\" LC_CTYPE=\"en_US.utf8\" ' \
  WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '${DB_NAME}')\gexec" \
  | $PSQL_CMD --username=${DB_USER}

# Run sql to create user and schema if they do not exist
$PSQL_CMD --username=${DB_USER} --dbname=${DB_NAME} -q << EOB
-- Create user if it does not exist
DO \$\$
BEGIN
  CREATE ROLE ${TAPIS_DB_USER} WITH LOGIN;
  EXCEPTION WHEN DUPLICATE_OBJECT THEN
  RAISE NOTICE 'User already exists. User name: ${TAPIS_DB_USER}';
END
\$\$;
ALTER USER ${TAPIS_DB_USER} WITH ENCRYPTED PASSWORD '${POSTGRES_PASSWORD}';
GRANT ALL PRIVILEGES ON DATABASE ${DB_NAME} TO ${TAPIS_DB_USER};

-- Create schema if it does not exist
CREATE SCHEMA IF NOT EXISTS ${TAPIS_DB_SCHEMA} AUTHORIZATION ${TAPIS_DB_USER};
ALTER ROLE ${TAPIS_DB_USER} SET search_path = '${TAPIS_DB_SCHEMA}';
EOB
