apiVersion: batch/v1
kind: Job
metadata:
  name: tms-server-sleep
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: tms-server-sleep
        image: tapis/tms-server:dev
        imagePullPolicy: Always
        securityContext:
          runAsUser: 0
          runAsGroup: 0
          runAsNonRoot: false
        command: ["/bin/sh", "-c"]
        args: ["sleep 6048000"]
        volumeMounts:
        - name: tms-server-vol
          mountPath: /home
      volumes:
      - name: tms-server-vol
        persistentVolumeClaim:
          claimName: tms-server-vol
  backoffLimit: 4
