# The project name gets an underscore appended to it and 
# then the whole string is prepended to named volumes.
# Specifically, "tms_" gets prepended to "docker_vol" below.
name: tms
services:
  tms_server:
    image: tapis/tms_server:${TMS_VERSION}
    container_name: tms_server_container
    environment:
      - HOME=/tms-root
    user: ${TMS_UID}:${TMS_GID}
    command: ["./tms_server", "--root-dir", "/tms-root/.tms"]
    ports:
      - "3000:3000"
    volumes:
      - docker_vol:/tms-root
      - type: bind
        source: ${HOME}/tms-docker/tms_customizations
        target: /tms-root/tms_customizations
      - /etc/group:/etc/group:ro
      - /etc/passwd:/etc/passwd:ro
      - /etc/shadow:/etc/shadow:ro
volumes:
  docker_vol:

