#!/bin/bash

kubectl apply -f pvc.yml
kubectl apply -f service.yml
kubectl apply -f deploy.yml

# Wait for postgres to finish coming up
kubectl wait --timeout=200s --for=condition=available deploy/tms-postgres-18
